server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rba
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:/db/migration

hr.rba.interview:
  active-document-location-path: documents/active
  processed-document-location-path: documents/processed